name: workflow

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    environment: Test
    container:
      image: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{vars.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          server-dir: test/todo/
          local-dir: dist/

      - name: Install Testcafe
        run: npm install -g testcafe

      - name: Update APT
        run: apt-get update

      - name: Install Chromium
        run: apt-get install -y chromium

      - name: Debug Current Directory
        run: |
          echo "--- PWD ---"
          pwd
          echo "--- Files in PWD (project root) ---"
          ls -a
          echo "--- Files UP ONE directory (parent) ---"
          ls -a ..

      - name: Run TestCafe E2E Tests
        run: npx testcafe "chromium:headless --no-sandbox --disable-dev-shm-usage --disable-gpu --ignore-certificate-errors" src/tests/* --page-request-timeout 20000 --concurrency 1 --browser-init-timeout 30000 --test-execution-timeout 180000 --skip-js-errors --host 0.0.0.0

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deployment:
    needs: integration-delivery
    runs-on: ubuntu-latest
    environment: Live
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: FTP deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{vars.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          server-dir: live/todo/
          local-dir: dist/
