name: workflow

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    environment: Test
    container:
      image: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: FTP delivery
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{vars.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          password: ${{secrets.FTP_PASSWORD}}
          server-dir: test/todo/
          local-dir: dist/

      - name: Install Testcafe
        run: npm instal -g testcafe

      - name: Update APT
        run: apt-get update

      - name: Install Chromium
        run: apt-get install -y chromium

      - name: Start dev server
        run: npm run dev &

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:5173

      - name: Run tests
        run: testcafe chromium:headless  src/tests/*
