name: workflow

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    enviroment: Test
    container:
      image: node
    steps:
      name: Checkout code
      uses: actions/checkout@v3

      name: Install dependencies
      run: npm Install

      name: Build website
      run: npm run build